# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/auth.proto\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32\x35\n\x04\x41uth\x12-\n\nCheckToken\x12\r.TokenRequest\x1a\x0e.TokenResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKENREQUEST._serialized_start=20
  _TOKENREQUEST._serialized_end=49
  _TOKENRESPONSE._serialized_start=51
  _TOKENRESPONSE._serialized_end=81
  _AUTH._serialized_start=83
  _AUTH._serialized_end=136
# @@protoc_insertion_point(module_scope)
