version: "3.10"


services:
  blockchain-service:
    build: ./services/blockchain
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./services/blockchain:/usr/src/app
      - ./proto:/usr/src/proto
    ports:
      - 8001:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@app-db:5432/app_db_dev
      - PYTHONPATH=/usr/src
    depends_on:
      - app-db
      - auth-service

  auth-service:
    build: ./services/auth
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./services/auth:/usr/src/app
      - ./db-models/models:/usr/src/models
      - ./proto:/usr/src/proto
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@app-db:5432/app_db_dev
      - PYTHONPATH=/usr/src
      - ACCESS_TOKEN_EXPIRE_MINUTES=10
    depends_on:
      - app-db

  app-db:
    build: ./services/db
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx-reverse-proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blockchain-service
      - auth-service
